
server:
  port: 9003

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'



dubbo:
  application:
    name: shopping_file_service
  registry:
    address: zookeeper://192.168.66.100
    port: 2181
    timeout: 10000
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.yhn.shopping_file_service.service

fdfs:
  so-timeout: 3000
  connect-timeout: 6000
  tracker-list:
    - 192.168.66.100:22122
  fileUrl: http://192.168.66.100

