
server:
  port: 9009

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'


spring:
  # redis
  redis:
    host: 192.168.66.100
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    # rabbitmq
  rabbitmq:
    host: 192.168.66.100
    port: 5672
    username: guest
    password: guest
    virtual-host: /

dubbo:
  application:
    name: shopping_cart_service
  registry:
    address: zookeeper://192.168.66.100
    port: 2181
    timeout: 10000
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.yhn.shopping_cart_service.service

